// react/src/components/Pagination.tsx
import clsx from 'clsx';
import React from 'react';
import { useSearchParams } from 'react-router-dom';
import { DEFAULT } from '~/constants/default';
import { SEARCH_PARAM_KEY } from '~/constants/key';

interface PaginationProps {
  total?: number;
}

export const Pagination = ({ total = 0 }: PaginationProps) => {
  const [searchParams, setSearchParams] = useSearchParams();

  const page = Number(searchParams.get(SEARCH_PARAM_KEY.PAGE) || 1);
  const limit = Number(searchParams.get(SEARCH_PARAM_KEY.LIMIT) || DEFAULT.PAGE_LIMIT);

  const totalPage = Math.ceil(total / limit);

  const handlePageChange = (currentPage: number) => {
    searchParams.set(SEARCH_PARAM_KEY.PAGE, currentPage.toString());
    setSearchParams(searchParams);
  };

  React.useEffect(() => {
    if (page > totalPage) handlePageChange(1);
  }, [total]);

  return (
    <div className="flex justify-center join">
      <button
        className={`join-item btn btn-sm ${clsx({ 'btn-disabled': page <= 1 })}`}
        onClick={() => handlePageChange(page - 1)}
      >
        «
      </button>
      <button className="join-item btn btn-sm">Page {page}</button>
      <button
        className={`join-item btn btn-sm ${clsx({ 'btn-disabled': page >= totalPage })}`}
        onClick={() => handlePageChange(page + 1)}
      >
        »
      </button>
    </div>
  );
};

export default Pagination;

// vue/src/components/Pagination.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { DEFAULT } from '~/constants/default'
import { SEARCH_PARAM_KEY } from '~/constants/key'

const props = defineProps<{ total: number }>()

const route = useRoute()
const router = useRouter()

const params = computed(() => {
  const { query } = route

  const [page, limit] = [
    Number(query[SEARCH_PARAM_KEY.PAGE] || 1),
    Number(query[SEARCH_PARAM_KEY.LIMIT] || DEFAULT.PAGE_LIMIT)
  ]

  return { page, limit, totalPage: Math.ceil(props.total / limit) }
})

const handlePageChange = (currentPage: number) => {
  router.push({ query: { ...route.query, [SEARCH_PARAM_KEY.PAGE]: currentPage.toString() } })
}
</script>

<template>
  <div class="flex justify-center join">
    <button
      class="join-item btn btn-sm"
      :class="{ 'btn-disabled': params.page <= 1 }"
      @click="handlePageChange(params.page - 1)"
    >
      «
    </button>
    <button class="join-item btn btn-sm">Page {{ params.page }}</button>
    <button
      class="join-item btn btn-sm"
      :class="{ 'btn-disabled': params.page >= params.totalPage }"
      @click="handlePageChange(params.page + 1)"
    >
      »
    </button>
  </div>
</template>
