// react/src/features/todo-list/components/LoadingSkeleton.tsx
import { DEFAULT } from '~/constants/default';

export const LoadingSkeleton = () => {
  return (
    <div className="flex flex-col gap-4 mx-4">
      {Array(DEFAULT.PAGE_LIMIT)
        .fill(1)
        .map((_, index) => (
          <div key={index} className="rounded-lg animate-pulse bg-base-200 h-[72px]"></div>
        ))}
    </div>
  );
};

export default LoadingSkeleton;

// vue/src/features/todo-list/LoadingSkeleton.vue
<script setup lang="ts">
import { DEFAULT } from '~/constants/default'
</script>

<template>
  <div class="flex flex-col gap-4">
    <div
      v-for="(_, index) in Array(DEFAULT.PAGE_LIMIT).fill(1)"
      :key="index"
      class="rounded-lg animate-pulse bg-base-200 h-16"
    ></div>
  </div>
</template>
