// react/src/features/category-list/components/LoadingSkeleton.tsx
export const LoadingSkeleton = () => {
  return (
    <div className="flex flex-wrap gap-4 px-4">
      {Array(12)
        .fill(1)
        .map((_, index) => (
          <div key={index} className="w-[55px] h-[55px] rounded-lg bg-base-200 animate-pulse" />
        ))}
    </div>
  );
};

export default LoadingSkeleton;

// vue/src/features/todo-list/LoadingSkeleton.vue
<script setup lang="ts">
import { DEFAULT } from '~/constants/default'
</script>

<template>
  <div class="flex flex-col gap-4">
    <div
      v-for="(_, index) in Array(DEFAULT.PAGE_LIMIT).fill(1)"
      :key="index"
      class="rounded-lg animate-pulse bg-base-200 h-16"
    ></div>
  </div>
</template>
