// react/src/features/todo-list/components/TodoFilter.tsx
import clsx from 'clsx';
import { useSearchParams } from 'react-router-dom';
import { SEARCH_PARAM_KEY } from '~/constants/key';

export type FilterValue = 'all' | 'active' | 'completed';

export const TodoFilter = () => {
  const [searchParams, setSearchParams] = useSearchParams();
  const filtered = (searchParams.get(SEARCH_PARAM_KEY.FILTER) as FilterValue) || 'all';

  const handleFilterChange = (filter: FilterValue) => {
    searchParams.set(SEARCH_PARAM_KEY.FILTER, filter);
    setSearchParams(searchParams);
  };

  const filters: Array<{ value: FilterValue; title: string; active: boolean }> = [
    { value: 'all', title: 'All', active: filtered !== 'active' && filtered !== 'completed' },
    { value: 'active', title: 'Active', active: filtered === 'active' },
    { value: 'completed', title: 'Completed', active: filtered === 'completed' }
  ];

  return (
    <div className="flex justify-between gap-2">
      {filters.map((item) => (
        <button
          key={item.value}
          className={clsx('btn btn-outline grow btn-sm btn-neutral', { 'btn-active btn-accent': item.active })}
          onClick={() => handleFilterChange(item.value)}
        >
          {item.title}
        </button>
      ))}
    </div>
  );
};

export default TodoFilter;

// vue/src/features/todo-list/TodoFilter.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { SEARCH_PARAM_KEY } from '~/constants/key'

export type FilterValue = 'all' | 'active' | 'completed'

const route = useRoute()
const router = useRouter()

const filters = computed<Array<{ value: FilterValue; title: string; active: boolean }>>(() => {
  const query = route.query
  const filtered = (query[SEARCH_PARAM_KEY.FILTER] || 'all') as FilterValue

  return [
    { value: 'all', title: 'All', active: filtered !== 'active' && filtered !== 'completed' },
    { value: 'active', title: 'Active', active: filtered === 'active' },
    { value: 'completed', title: 'Completed', active: filtered === 'completed' }
  ]
})

const handleFilterChange = (filter: FilterValue) => {
  router.push({ query: { ...route.query, [SEARCH_PARAM_KEY.FILTER]: filter } })
}
</script>

<template>
  <div class="flex justify-between gap-2">
    <button
      v-for="filter in filters"
      :key="filter.value"
      class="btn btn-outline grow btn-sm btn-neutral"
      :class="{ 'btn-active btn-accent': filter.active }"
      @click="handleFilterChange(filter.value)"
    >
      {{ filter.title }}
    </button>
  </div>
</template>
