// react/src/components/layouts/MainLayout.tsx
import React from 'react';
import { Outlet } from 'react-router-dom';
import BottomNavigation from './BottomNavigation';
import TopBar from './TopBar';

export const MainLayout = () => {
  return (
    <div className="max-w-[375px] mx-auto my-8 overflow-hidden shadow-lg rounded-2xl bg-base-300">
      <TopBar />

      <div className="flex-grow h-[450px] my-4 overflow-auto">
        <React.Suspense fallback={null}>
          <Outlet />
        </React.Suspense>
      </div>

      <BottomNavigation />
    </div>
  );
};

export default MainLayout;

// vue/src/components/layouts/MainLayout.vue
<script setup lang="ts">
import { RouterView } from 'vue-router'
import BottomNavigation from './bottom/BottomNavigation.vue'
import TopBar from './TopBar.vue'
</script>

<template>
  <div class="max-w-[375px] mx-auto my-8 overflow-hidden shadow-lg rounded-2xl bg-base-300">
    <TopBar />

    <div class="flex-grow h-[500px] my-4 overflow-auto">
      <RouterView />
    </div>

    <BottomNavigation />
  </div>
</template>
