// vue/src/components/ThemeController.vue
<script setup lang="ts">
import { storeToRefs } from 'pinia'
import { useThemeMode } from '~/stores/theme'

const themeStore = useThemeMode()
const { toggleTheme } = themeStore

const mode = storeToRefs(themeStore).mode
</script>

<template>
  <label class="swap swap-rotate">
    <input type="checkbox" class="theme-controller" @change="toggleTheme" />
    <span v-if="mode === 'dark'" class="icon-[ph--sun-fill] w-6 h-6 text-base-content"></span>
    <span v-else class="icon-[ph--moon-fill] w-6 h-6 text-base-content"></span>
  </label>
</template>

// react/src/components/ThemeController.tsx
import { useThemeMode } from '~/stores/theme';

export const ThemeController = () => {
  const toggleTheme = useThemeMode((state) => state.toggleTheme);
  const mode = useThemeMode((state) => state.mode);

  return (
    <label className="swap swap-rotate">
      <input type="checkbox" className="theme-controller" onChange={toggleTheme} />
      {mode === 'dark' ? (
        <span className="icon-[ph--sun-fill] w-6 h-6 text-base-content"></span>
      ) : (
        <span className="icon-[ph--moon-fill] w-6 h-6 text-base-content"></span>
      )}
    </label>
  );
};

export default ThemeController;
