// react/src/features/category-list/index.tsx
import { useQuery } from '@tanstack/react-query';
import { fetcher } from '~/configs/query-client';
import { ENDPOINT } from '~/constants/endpoint';
import { QUERY_KEY } from '~/constants/key';
import { Category } from '~/types/Category';
import NewCategory from '../new-category';
import CategoryItem from './components/CategoryItem';
import LoadingSkeleton from './components/LoadingSkeleton';

export const CategoryList = () => {
  const { data: categories = [], isLoading } = useQuery({
    queryKey: [QUERY_KEY.CATEGORIES],
    queryFn: fetcher<Category[]>(ENDPOINT.GET_CATEGORIES)
  });

  if (isLoading) return <LoadingSkeleton />;

  return (
    <div className="grid grid-cols-4 gap-4 px-4">
      {categories.map((category) => (
        <CategoryItem key={category.id} {...category} />
      ))}

      <NewCategory />
    </div>
  );
};

export default CategoryList;

// vue/src/features/category-list/CategoryList.vue
<script setup lang="ts">
import { useQuery } from '@tanstack/vue-query'
import { fetcher } from '~/configs/query-client'
import { ENDPOINT } from '~/constants/endpoint'
import { QUERY_KEY } from '~/constants/key'
import type { Category } from '~/types/Category'
import NewCategory from '../new-category/NewCategory.vue'
import CategoryItem from './CategoryItem.vue'
import LoadingSkeleton from './LoadingSkeleton.vue'

const { data: categories = [], isLoading } = useQuery({
  queryKey: [QUERY_KEY.CATEGORIES],
  queryFn: fetcher<Category[]>(ENDPOINT.GET_CATEGORIES)
})
</script>

<template>
  <LoadingSkeleton v-if="isLoading" />
  <div v-else class="grid grid-cols-4 gap-4 px-4">
    <template v-if="categories?.length">
      <CategoryItem v-for="category in categories" :key="category.id" :="category" />
    </template>

    <NewCategory />
  </div>
</template>
