// react/src/features/new-todo/index.tsx
import clsx from 'clsx';
import React from 'react';
import NewTodoForm from './components/NewTodoForm';

export const NewTodo = () => {
  const [open, setOpen] = React.useState(false);

  return (
    <React.Fragment>
      <button
        className="relative w-16 h-16 drawer-button -top-11 btn btn-circle btn-primary"
        onClick={() => {
          setOpen(true);
        }}
      >
        <span className="icon-[ph--plus] w-8 h-8 text-gray-300"></span>
      </button>

      <dialog className={`modal ${clsx({ 'modal-open': open })}`}>
        <div className="relative w-80 modal-box -top-20">
          <div className="flex items-center justify-between">
            <h3 className="text-lg font-bold">New task</h3>
            <button className="btn btn-sm btn-circle btn-ghost" onClick={() => setOpen(false)}>
              ✕
            </button>
          </div>
          <NewTodoForm onSuccess={() => setOpen(false)} />
        </div>
      </dialog>
    </React.Fragment>
  );
};

export default NewTodo;

// vue/src/features/new-todo/NewTodo.vue
<script setup lang="ts">
import { defineAsyncComponent, ref } from 'vue'
import Loading from '~/components/Loading.vue'
const NewTodoForm = defineAsyncComponent({ loader: () => import('./NewTodoForm.vue'), loadingComponent: Loading })

const open = ref(false)
</script>

<template>
  <button class="relative w-16 h-16 drawer-button -top-11 btn btn-circle btn-primary" @click="open = true">
    <span class="icon-[ph--plus] w-8 h-8 text-gray-300"></span>
  </button>

  <dialog class="modal" :class="{ 'modal-open': open }">
    <div class="relative w-80 modal-box -top-20">
      <div class="flex items-center justify-between">
        <h3 class="text-lg font-bold">New task</h3>
        <button class="btn btn-sm btn-circle btn-ghost" @click="open = false">✕</button>
      </div>

      <NewTodoForm v-if="open" @success="open = false" />
    </div>
  </dialog>
</template>
